# Generated by Django 3.1.6 on 2021-02-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210218_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='supercategory',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category'),
        ),
        migrations.DeleteModel(
            name='SuperCategory',
        ),
    ]
