# Generated by Django 3.1.6 on 2021-02-26 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210225_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('product',)},
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shop.attributebase')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shop.product')),
            ],
            bases=('shop.attribute',),
        ),
    ]
