# Generated by Django 3.1.6 on 2021-02-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210226_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shop.producttype'),
        ),
        migrations.AlterField(
            model_name='attributebase',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
