# Generated by Django 3.1.6 on 2021-02-26 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210226_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='product_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='shop.producttype'),
        ),
    ]
