# Generated by Django 3.1.6 on 2021-02-27 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210227_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PDF',
            field=models.FileField(blank=True, null=True, upload_to='pdf/fiches techniques/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
