# Generated by Django 3.1.6 on 2021-03-02 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210227_1112'),
        ('orders', '0005_auto_20210302_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items_type', to='shop.producttype'),
        ),
    ]
